=== kimntnguyen236/XML-JSON/Project1/src/Homework/Schema/tv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:ns="http://xml.netbeans.org/examples/targetNS"
targetNamespace="http://xml.netbeans.rg/examples/targetNs"
xmlns="http://xml.netbeans.org/examples/targetNS" 
elementFormDefault="qualified">
<xsd:element name="tv-list">
<xsd:complexType>
<xsd:sequence minOccurs='0' maxOccurs='1000'>
    <xsd:element name="tv">
    <xsd:complexType>
    <xsd:sequence>
        <xsd:element name="namne">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:minLength value='2'/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:element>
<!-- nha san xuât là một chuỗi độ đài >=2 => the don -->
<xsd:element name="manufacturer">
<xsd:simpleType>
<xsd:restriction base='xsd:string'>
<xsd:minLength value="2"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<!-- gia: s6 float: )0.0,1000.0[ -->
<xsd:element name="price">
<xsd:simpleType>
<xsd:restriction base="xsd:float">
<xsd:minExclusive value="0.0"/>
<xsd:maxExclusive value="1000.0"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="guarantee">
<xsd:simpleType>
<xsd:restriction base="xsd:short">
<xsd:minExclusive value="0"/>
<xsd:maxExclusive value="37"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== kimntnguyen236/XML-JSON/Project1/src/Homework/Schema/tv-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:tv-list
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://xml.netbeans.rg/examples/targetNs'
    xsi:schemaLocation='http://xml.netbeans.rg/examples/targetNs tv.xsd'>
    <ns1:tv>
        <ns1:namne>LG 32 inches</ns1:namne>
        <ns1:manufacturer>LG</ns1:manufacturer>
        <ns1:price>350.5</ns1:price>
        <ns1:guarantee>24</ns1:guarantee>
    </ns1:tv>
     <ns1:tv>
        <ns1:namne>TCL 32 inches</ns1:namne>
        <ns1:manufacturer>TCL</ns1:manufacturer>
        <ns1:price>750.5</ns1:price>
        <ns1:guarantee>22</ns1:guarantee>
    </ns1:tv>
    <ns1:tv>
        <ns1:namne>HP 32 inches</ns1:namne>
        <ns1:manufacturer>HP</ns1:manufacturer>
        <ns1:price>390</ns1:price>
        <ns1:guarantee>20</ns1:guarantee>
    </ns1:tv>
</ns1:tv-list>
