=== kimntnguyen236/XML-JSON/Project1/src/Homework/DTD/Document.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT DOCUMENT (CUSTOMER)*>
<!ELEMENT CUSTOMER (NAME|DATE|ORDERS)*>
<!ATTLIST CUSTOMER 
        TYPE CDATA #IMPLIED
>

<!ELEMENT NAME (LASTNAME|FIRSTNAME)*>
<!ELEMENT LASTNAME (#PCDATA)>
<!ELEMENT FIRSTNAME (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT ORDERS (ITEM)*>
<!ATTLIST ORDERS 
        class CDATA #IMPLIED
>
<!ELEMENT ITEM (PRODUCT|NUMBER|PRICE)*>
<!ELEMENT PRODUCT (#PCDATA|PRODUCTID)*>
<!ELEMENT PRODUCTID (#PCDATA)>
<!ELEMENT NUMBER (#PCDATA)>
<!ELEMENT PRICE (#PCDATA)>

=== kimntnguyen236/XML-JSON/Project1/src/Homework/DTD/Document.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE DOCUMENT SYSTEM "Document.dtd">
<DOCUMENT>
    <CUSTOMER TYPE="Good">
        <NAME>
            <LASTNAME>aaa</LASTNAME>
            <FIRSTNAME>bbb</FIRSTNAME>
        </NAME>
        <DATE>1/1/03</DATE>
        <ORDERS class="SanPham">
            <ITEM>
                <PRODUCT>
                    <PRODUCTID>12</PRODUCTID>
                </PRODUCT>
                <NUMBER>25</NUMBER>
                <PRICE>20</PRICE>
            </ITEM>
            <ITEM>
                <PRODUCT>Tomatoes</PRODUCT>
                <NUMBER>25</NUMBER>
                <PRICE>3</PRICE>
            </ITEM>
        </ORDERS>
    </CUSTOMER>
</DOCUMENT>
